#! /bin/sh
# /etc/init.d/_clientautorun_

### BEGIN INIT INFO
# Provides:		noip
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: Simple bash script to start a program ot boot
# Description: A simple bash script to auto connect internet and start EITS client side automatically at boot
### END INIT INFO

case "$1" in
   start)
	  sleep 10
	  echo "connecting via wvdial"
	  (sudo wvdial 3gconnect &) && sleep 10 && python /home/pi/eits/client.py
	;;
   stop)
	  echo "disconnecting via wvdial"
	;;
   *)
    echo "Usage: /etc/init.d/_clientautorun_ {start|stop}"
	exit 1
	;;
esac
exit 0
