#! /bin/sh
# /etc/init.d/_serverautorun_

### BEGIN INIT INFO
# Provides:		noip
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: Simple bash script to start a program ot boot
# Description: A simple bash script to start EITS server side automatically at boot
### END INIT INFO

case "$1" in
   start)
	  sleep 10
	  echo "auto connecting server.py "
    python /EITS/server.py
	;;
   stop)
	  echo "disconnecting server.py"
	;;
   *)
    echo "Usage: /etc/init.d/_serverautorun_ {start|stop}"
	exit 1
	;;
esac
exit 0
